source 'https://rubygems.org'

puppetversion =
  ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['~> 3.8']
gem 'puppet', puppetversion
gem 'puppetlabs_spec_helper', '>= 0.1.0'
gem 'puppet-lint', '>= 0.3.2'
gem 'facter', '>= 1.7.0'

gem 'rspec-puppet'
gem 'puppet-syntax'
gem 'rubocop'
gem 'hiera'
gem 'hiera-puppet'
gem 'rspec-hiera-puppet'
gem 'hiera-puppet-helper'
gem 'rake'
gem 'rspec'
gem 'rspec-puppet-facts', require: false
gem 'beaker'
gem 'nokogiri'
gem 'r10k'
